inherit_from: .rubocop_todo.yml

Style/Documentation:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/IndentArray:
  EnforcedStyle: consistent
Metrics/BlockLength:
  Exclude:
    - 'db/**/*.rb'
Metrics/MethodLength:
  Exclude:
    - 'db/**/*.rb'
Metrics/AbcSize:
  Exclude:
    - 'db/**/*.rb'
Style/MixinUsage:
  Exclude:
    - 'bin/*'
Style/WordArray:
  Exclude:
    - 'db/schema.rb'
