form:
  name: 'Continue'
  template: :check_if_you_can_foster
  steps:
    # fostering_type:
    #   template: :questions
    #   questions:
    #     - name: :section
    #       heading: Check if you can be a foster carer
    #       title: What type of fostering are you interested in?
    #       widget: :title
    #     - name: :type_of_fostering
    #       widget: :checkbox
    #       answers:
    #         - title: Emergency Fostering
    #           value: :emergency_fostering
    #         - title: Short Term Fostering
    #           value: :short_term_fostering
    #         - title: Long Term Fostering
    #           value: :long_term_fostering
    #         - title: Don't Know
    #           value: :dont_know
    age:
      template: :single_question
      next_step: :next_step
      questions:
        - name: :section
          title: Are you over 21 years of age?
          widget: :title
        - name: :over_21
          widget: :boolean
    spare_room:
      template: single_question
      next_step: :experience
      questions:
        - name: :section
          title: Do you have a spare room?
          widget: :title
        - name: :spare_room
          widget: :radio
    housing_type:
      template: :questions
      help: help
      questions:
        - name: :section
          title: What type of housing do you live in?
          widget: :title
        - name: :housing_type
          widget: :radio
    experience:
      template: :single_question
      next_step: :age_experience
      questions:
        - name: :section
          title: How much childcare experience do you have?
          widget: :title
        - name: :experience
          widget: :radio
    age_experience:
      template: :single_question
      questions:
        - name: :section
          title: What age group do you have the most experience with?
          widget: :title
        - name: :age_experience
          widget: :checkbox
          answers:
            - title: 0-2 years old
              value: :0_2
            - title: 2-10 years old
              value: :2_10
            - title: 11-18 years old
              value: :11_18
    be_in_touch:
      template: :questions
      questions:
        - name: :section
          title: You're eligible to apply to be a foster carer
          widget: :title
        - name: :section
          content: Based on your answers you're eligible to be a foster carer. Thank you for taking the time, if you're interested in speaking to our fostering team then enter your contact details.
          widget: :text
        - name: :be_in_touch
          title: Would you be interested in speaking to someone from our fostering team?
          with_title: true
          widget: :radio
    other_ways:
      template: :single_question
      questions:
        - name: :section
          notice_title: Unfortunately you're not eligible to be a foster carer at the moment.
          notice: Having a spare room and being over the age of 21 is a requirement to becoming a foster carer.
          widget: :notice
          h2_title: Would you like to find out other ways of helping young people in Hackney?
        - name: :section
          widget: text
          content: If you're interested in finding out about other ways of supporting children and young people in Hackney then please enter your contact details below, and someone from our team will be in contact with you.

    what_is_your_name:
      template: :questions
      questions:
        - name: :section
          widget: :title
          title: Your details
        - name: :first_name
          title: First name
          widget: :input
          with_title: true
          model: :applicant
        - name: :last_name
          title: Last name
          widget: :input
          with_title: true
          model: :applicant
    address:
      template: :questions
      questions:
        - name: :postcode
          model: :address
          title: Enter your home postcode?
          widget: :find_input
    contacting_you:
      template: single_question
      next_step: :next_step
      questions:
        - name: :section
          title: What's the best way for us to contact you?
          widget: :title
        - name: :contacting_you
          widget: :radio
    contact_phone:
      template: :questions
      next_step: :contact_phone_time
      questions:
        - name: :phone_number
          title: Phone number
          widget: :tel
    contact_phone_time:
      template: :questions
      next_step: :contact_email
      questions:
        - name: :section
          title: When can we contact you?
          widget: :title
        - name: :contact_phone_time
          widget: :checkbox
          answers:
            - title: Morning
              value: :morning
            - title: Afternoon
              value: :afternoon
    contact_email:
      template: :questions
      next_step: :thank_you
      questions:
        - name: :section
          widget: :title
        - name: :email
          title: Email address
          widget: :email
          model: :applicant
    thank_you:
      template: :thank_you
