form:
  name: 'Continue'
  template: :check_if_you_can_foster
  steps:
    fostering_type:
      template: :questions
      questions:
        - name: :section
          heading: Check if you can be a foster carer
          title: What type of fostering are you interested in?
          widget: :title
        - name: :type_of_fostering
          widget: :checkbox
          answers:
            - title: Emergency Fostering
              value: :emergency_fostering
            - title: Short Term Fostering
              value: :short_term_fostering
            - title: Long Term Fostering
              value: :long_term_fostering
            - title: Don't Know
              value: :dont_know
    spare_room:
      template: single_question
      next_step: :next_step
      questions:
        - name: :section
          heading: Check if you can be a foster carer
          title: Do you have a spare room?
          widget: :title
        - name: :spare_room
          widget: :radio
    over_21:
      template: :single_question
      next_step: :experience
      questions:
        - name: :section
          heading: Check if you can be a foster carer
          widget: :title
        - name: :section
          title: Are you over 21 years of age?
          widget: :title
        - name: :over_21
          widget: :boolean
    experience:
      template: :single_question
      next_step: :age_experience
      questions:
        - name: :section
          heading: Check if you can be a foster carer
          widget: :title
        - name: :section
          title: How experienced are you working with children or young people?
          widget: :title
        - name: :experience
          widget: :radio
    age_experience:
      template: :single_question
      next_step: :housing_type
      questions:
        - name: :section
          heading: Check if you can be a foster carer
          widget: :title
        - name: :section
          title: What age of children have you had the most experience with?
          widget: :title
        - name: :age_experience
          widget: :checkbox
          answers:
            - title: 0-2 years old
              value: :0_2
            - title: 2-10 years old
              value: :2_10
            - title: 11-18 years old
              value: :11_18
    housing_type:
      template: :questions
      help: help
      questions:
        - name: :section
          heading: Check if you can be a foster carer
          widget: :title
        - name: :section
          title: What type of housing do you live in?
          widget: :title
        - name: :housing_type
          widget: :radio
    be_in_touch:
      template: :questions
      questions:
        - name: :section
          heading: You have the potential to be a foster carer
          widget: :title
        - name: :section
          title: Would you be interested in speaking to someone from the fostering team?
          widget: :title
        - name: :be_in_touch
          widget: :radio
    other_ways:
      template: :single_question
      questions:
        - name: :section
          heading: Check if you can be a foster carer
          notice: Sorry, you are unable to be a foster carer at the moment.
          title: Other ways you can help children and young people in Hackney
          widget: :notice
        - name: :other_ways
          title: Sorry, you are unable to be a foster carer at the moment
          widget: :radio
          next_button_label: Provide contact details
    what_is_your_name:
      template: :questions
      questions:
        - name: :section
          heading: Check if you can be a foster carer
          title: What is your full name?
          widget: :title
        - name: :first_name
          title: First name(s)
          widget: :input
          model: :applicant
        - name: :last_name
          title: Last name
          widget: :input
          model: :applicant
    address:
      template: :questions
      questions:
        - name: :section
          heading: Check if you can be a foster carer
          title: What is your postcode?
          widget: :title
        - name: :postcode
          model: :address
          title: Enter your postcode
          widget: :find_input
    contacting_you:
      template: single_question
      next_step: :next_step
      questions:
        - name: :section
          heading: Check if you can be a foster carer
          title: What is the best way for us to contact you?
          widget: :title
        - name: :contacting_you
          widget: :radio
    contact_phone:
      template: :questions
      next_step: :contact_phone_time
      questions:
        - name: :contact_phone
          heading: Check if you can be a foster carer
          title: What is your phone number?
          widget: :title
        - name: :phone_number
          title: Enter your phone number
          widget: :tel
    contact_phone_time:
      template: :questions
      next_step: :thank_you
      questions:
        - name: :section
          heading: Check if you can be a foster carer
          title: When is a good time to contact you?
          widget: :title
        - name: :contact_phone_time
          widget: :radio
    contact_email:
      template: :questions
      next_step: :thank_you
      questions:
        - name: :section
          heading: Check if you can be a foster carer
          widget: :title
        - name: :contact_email
          title: What is your email address?
          widget: :title
        - name: :email
          title: Enter your email address
          widget: :email
    thank_you:
      template: :thank_you
