form:
  name: 'Continue'
  template: :check_if_you_can_foster
  steps:
    what_is_your_name:
      template: :questions
      title: Tell us about yourself
      help: help
      next_question: :gender
      questions:
        - name: :section
          heading: Tell us about yourself
          intro: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..
          widget: :title
        - name: :sub_section
          title: What is your full name?
          widget: :title
        - name: :name
          title: First name(s)
          widget: :input
        - name: :last_name
          title: Last name
          widget: :input
    gender:
      template: :single_question
      title: Gender
      help: help
      next_question: :dob
      questions:
        - name: :section
          heading: Tell us about yourself
          intro: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..
          widget: :title
        - name: :sub_section
          title: Gender
          widget: :title
        - name: :gender
          widget: :radio
          answers:
            - title: Female
              value: :female
              help: help
            - title: Male
              value: :male
              help: help
            - title: Unspecified
              value: :unspecified
              help: help
    dob:
      template: :questions
      title: Date of birth
      help: help
      next_question: :are_you_practicing
      questions:
        - name: :section
          heading: Tell us about yourself
          intro: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..
          widget: :title
        - name: :sub_section
          title: Date of birth
          widget: :title
        - name: :day
          title: Day
          widget: :day
          help: help
        - name: :month
          title: Month
          widget: :month
          help: help
        - name: :year
          title: Year
          widget: :year
          help: help
    are_you_practicing:
      template: :questions
      title: Are you practicing?
      help: help
      next_question: :what_do_you_practice
      rules:
        are_you_practicing:
          practicing: :what_do_you_practice
          non_practicing: :language
      questions:
        - name: :section
          heading: Tell us about yourself
          intro: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..
          widget: :title
        - name: :sub_section
          title: Are you practicing?
          widget: :title
        - name: :are_you_practicing
          title: Other
          widget: :radio
          answers:
            - title: Practicing
              value: :practicing
            - title: Non-practicing
              value: :non_practicing
    what_do_you_practice:
      template: :questions
      title: What religion do you practice?
      help: help
      next_question: :language
      questions:
        - name: :section
          heading: Tell us about yourself
          intro: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..
          widget: :title
        - name: :sub_section
          title: What religion do you practice?
          widget: :title
        - name: :what_do_you_practice
          title: What religion do you practice?
          widget: :checkbox
          answers:
            - title: Christianity
              value: :Christianity
              help: help
            - title: Judaism
              value: :judaism
              help: help
            - title: Buddhism
              value: :buddhism
              help: help
        - name: :what_do_you_practice
          title: Other
          widget: :input
        - name: :what_do_you_practice
          title: What are your religious beliefs?
          widget: :input
    language:
      template: questions
      title: What is your primary language?
      help: help
      next_question: :nationality
      questions:
        - name: :section
          heading: Tell us about yourself
          intro: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..
          widget: :title
        - name: :sub_section
          title: What is your primary language?
          widget: :title
        - name: :language
          title: What is your primary language?
          widget: :radio
          answers:
            - title: English
              value: :english
            - title: German
              value: :german
            - title: French
              value: :french
        - name: :language
          title: What other languages are spoken at home?
          widget: :input
    nationality:
      template: questions
      title: What is your nationality?
      help: help
      next_question: :address
      questions:
        - name: :section
          heading: Tell us about yourself
          intro: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..
          widget: :title
        - name: :sub_section
          title: What is your nationality?
          widget: :title
        - name: :language
          title: What is your nationality?
          widget: :radio
          answers:
            - title: English
              value: :english
            - title: British
              value: :british
            - title: German
              value: :german
            - title: French
              value: :french
        - name: :nationality
          title: Other
          widget: :input
    address:
      template: :questions
      title: Tell us about your home
      help: help
      next_question: :address_period
      questions:
        - name: :section
          heading: Tell us about your home
          intro: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..
          widget: :title
        - name: :sub_section
          title: What is your postcode?
          widget: :title
        - name: :name
          title: Find your address
          widget: :input
    address_period:
      template: :questions
      title: Tell us about your home
      help: help
      next_question: :previous_address
      questions:
        - name: :section
          heading: Tell us about your home
          intro: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..
          widget: :title
        - name: :sub_section
          title: When did you move into this property?
          widget: :title
        - name: :day
          title: Day
          widget: :day
          help: help
        - name: :month
          title: Month
          widget: :month
          help: help
        - name: :year
          title: Year
          widget: :year
          help: help
    previous_address:
      template: :questions
      title: Tell us about your previous address
      help: help
      next_question: :previous_address_period
      questions:
        - name: :section
          heading: Tell us about your previous address
          intro: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..
          widget: :title
        - name: :sub_section
          title: What is your previous postcode?
          widget: :title
        - name: :name
          title: Find your previous address
          widget: :input
    previous_address_period:
      template: :questions
      title: Tell us about your previous address
      help: help
      next_question: :children_living_at_home
      questions:
        - name: :section
          heading: Tell us about your previous address
          intro: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..
          widget: :title
        - name: :sub_section
          title: When did you move into this previous property?
          widget: :title
        - name: :day
          title: Day
          widget: :day
          help: help
        - name: :month
          title: Month
          widget: :month
          help: help
        - name: :year
          title: Year
          widget: :year
          help: help
    children_living_at_home:
      template: questions
      title: Living at home
      help: help
      next_question: :other_children_living_at_home
      questions:
        - name: :section
          heading: Tell about who lives in your home
          intro: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..
          widget: :title
        - name: :sub_section
          title: Are there any children under 18 living in the household?
          widget: :title
        - name: name
          widget: :boolean
          yes_value: Yes
          no_value: Yes
        - name: :name
          title: How many?
          widget: :input
    other_children_living_at_home:
      template: questions
      title: Living at home
      help: help
      next_question: :adults_living_at_home
      questions:
        - name: :section
          heading: Tell about who lives in your home
          intro: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..
          widget: :title
        - name: :sub_section
          title: Are there children (under 18) from a current or previous relationship living elsewhere?
          widget: :title
        - name: name
          widget: :boolean
          yes_value: Yes
          no_value: Yes
        - name: :name
          title: How many?
          widget: :input
    adults_living_at_home:
      template: questions
      title: Living at home
      help: help
      next_question: :children_living_at_home_name
      questions:
        - name: :section
          heading: Tell about who lives in your home
          intro: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..
          widget: :title
        - name: :sub_section
          title: Are there any adults living in the household?
          widget: :title
        - name: name
          widget: :boolean
          yes_value: Yes
          no_value: Yes
        - name: :name
          title: How many?
          widget: :input
    children_living_at_home_name:
      template: :questions
      title: Tell us about yourself
      help: help
      next_question: :children_living_at_home_gender
      questions:
        - name: :section
          heading: Tell us about the children in your home
          intro: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..
          widget: :title
        - name: :sub_section
          title: What is the childs name?
          widget: :title
        - name: :name
          title: First name(s)
          widget: :input
        - name: :last_name
          title: Last name
          widget: :input
    children_living_at_home_gender:
      template: :single_question
      title: Gender
      help: help
      next_question: :children_living_at_home_dob
      questions:
        - name: :section
          heading: Tell us about the children in your home
          intro: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..
          widget: :title
        - name: :sub_section
          title: Gender
          widget: :title
        - name: :gender
          widget: :radio
          answers:
            - title: Female
              value: :female
              help: help
            - title: Male
              value: :male
              help: help
            - title: Unspecified
              value: :unspecified
              help: help
    children_living_at_home_dob:
      template: :questions
      title: Date of birth
      help: help
      next_question: :living_in_your_home
      questions:
        - name: :section
          heading: Tell us about the children in your home
          intro: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..
          widget: :title
        - name: :sub_section
          title: Date of birth
          widget: :title
        - name: :day
          title: Day
          widget: :day
          help: help
        - name: :month
          title: Month
          widget: :month
          help: help
        - name: :year
          title: Year
          widget: :year
          help: help
        - name: :relationship
          title: Relationship to applicant
          widget: :input
    living_in_your_home:
      template: :questions
      title: Tell us who lives in your home
      help: help
      next_question: :are_you_practicing
      questions:
        - name: :section
          heading: Tell us who lives in your home
          intro: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..
          widget: :title
        - name: :sub_section
          title: Where does your child go to school?
          widget: :title
        - name: :name
          title: Find school address
          widget: :input
        - name: :name
          title: Please provide the phone number
          widget: :input
    adults_living_at_home_name:
      template: :questions
      title: Tell us about the other adults in your home
      help: help
      next_question: :adults_living_at_home_gender
      questions:
        - name: :section
          heading: Tell us about the other adults in your home
          intro: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..
          widget: :title
        - name: :sub_section
          title: What is the adults name?
          widget: :title
        - name: :name
          title: First name(s)
          widget: :input
        - name: :last_name
          title: Last name
          widget: :input
    adults_living_at_home_gender:
      template: :single_question
      title: Gender
      help: help
      next_question: :adults_living_at_home_dob
      questions:
        - name: :section
          heading: Tell us about the adults in your home
          intro: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..
          widget: :title
        - name: :sub_section
          title: Gender
          widget: :title
        - name: :gender
          widget: :radio
          answers:
            - title: Female
              value: :female
              help: help
            - title: Male
              value: :male
              help: help
            - title: Unspecified
              value: :unspecified
              help: help
    adults_living_at_home_dob:
      template: :questions
      title: Date of birth
      help: help
      next_question: :pets
      questions:
        - name: :section
          heading: Tell us about the adults in your home
          intro: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..
          widget: :title
        - name: :sub_section
          title: Date of birth
          widget: :title
        - name: :day
          title: Day
          widget: :day
          help: help
        - name: :month
          title: Month
          widget: :month
          help: help
        - name: :year
          title: Year
          widget: :year
          help: help
        - name: :relationship
          title: Relationship to applicant
          widget: :input
    pets:
      template: :single_question
      title: Pets
      help: help
      next_question: :pet_size
      questions:
        - name: :section
          heading: Pets
          intro: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..
          widget: :title
        - name: :sub_section
          title: Do you have any pets?
          widget: :title
        - name: name
          widget: :boolean
          yes_value: Yes
          no_value: Yes
        - name: :name
          title: What type of pets do you have?
          widget: :input
        - name: :name
          title: What breed/species is your pet?
          widget: :input
    pet_size:
      template: :single_question
      title: Pets
      help: help
      next_question: :pet_neutered
      questions:
        - name: :section
          heading: Pets
          intro: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..
          widget: :title
        - name: :sub_section
          title: What is the size of your pet?
          widget: :title
        - name: :size
          widget: :radio
          answers:
            - title: Small
              value: :small
              help: help
            - title: Medium
              value: :medium
              help: help
            - title: Large
              value: :large
              help: help
    pet_neutered:
      template: :single_question
      title: Pets
      help: help
      questions:
        - name: :section
          heading: Pets
          intro: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..
          widget: :title
        - name: :sub_section
          title: Has your pet been neutered?
          widget: :title
        - name: :neutered
          widget: :boolean
          yes_value: Yes
          no_value: Yes
