form:
  name: 'Legal History'
  template: :check_if_you_can_foster
  steps:
    intro:
      template: :single_question
      questions:
        - name: :section
          title: Tell us your legal history
          widget: :title
        - name: :sub_section
          info: |
            Safety is important for the foster child, knowing if you have been
            in a family court proceeding is essential. Please provide as much
            detail as possible.

            We may contact the related council to get further information (with your consent).
          widget: :title
    family_court:
      template: :single_question
      questions:
        - name: :sub_section
          title: Have you ever been in any family court proceeding or in any proceedings about children and/or family?
          current_section: Legal history
          widget: :title
        - name: :family_court
          widget: :boolean
          yes_value: Yes
          no_value: No
    court_date:
      template: :single_question
      questions:
        - name: :sub_section
          title: Date of court proceeding
          current_section: Legal history
          widget: :title
        - name: :court_date
          with_title: true
          widget: :date
    court_name:
      template: :single_question
      questions:
        - name: :court_name
          title: Name of local authority
          current_section: Legal history
          widget: :input
    type_of_order:
      template: :single_question
      questions:
        - name: :type_of_order
          current_section: Legal history
          widget: :input
          title: Type of order made
    parties_involved:
      template: :single_question
      questions:
        - name: :parties_involved
          title: Full names of all children or adults involved
          current_section: Legal history
          widget: :textarea
    court_details:
      template: :single_question
      questions:
        - name: :court_details
          title: Details of the case
          current_section: Legal history
          widget: :textarea
    previous_applications:
      template: :single_question
      questions:
        - name: :sub_section
          title: Have you previously applied to become a foster carer, adopter or child-minder?
          current_section: Legal history
          widget: :title
        - name: :previous_applications
          widget: :boolean
          yes_value: Yes
          no_value: No
    application_date:
      template: :single_question
      questions:
        - name: :sub_section
          title: Date you applied
          current_section: Legal history
          widget: :title
        - name: :application_date
          with_title: true
          widget: :date
    agency_name:
      template: :single_question
      questions:
        - name: :agency_name
          title: Name of agency or service
          current_section: Legal history
          widget: :input
    agency_address:
      template: :single_question
      template: :address
      reference: :agency_address
      current_section: Legal history
      title: Address of agency or service
      questions:
        - name: :line_1
          title: Address Line 1
          with_title: true
          widget: :input
          model: :address
        - name: :line_2
          title: Address Line 2
          with_title: true
          widget: :input
          model: :address
        - name: :line_3
          title: Address Line 3
          with_title: true
          widget: :input
          model: :address
        - name: :post_town
          title: Address Line 4
          with_title: true
          widget: :input
          model: :address
        - name: :postcode
          title: Postcode
          with_title: true
          widget: :input
    type_of_application:
      template: :single_question
      questions:
        - name: :type_of_application
          title: Type of application
          current_section: Legal history
          widget: :input
    application_outcome:
      template: :single_question
      questions:
        - name: :application_outcome
          title: What was the outcome of the application?
          current_section: Legal history
          widget: :textarea
    other_previous_applications:
      template: :single_question
      questions:
        - name: :sub_section
          title: Has any member of your household previously applied to become a foster carer, adopter or child-minder?
          current_section: Legal history
          widget: :title
        - name: :other_previous_applications
          widget: :boolean
          yes_value: Yes
          no_value: No
    other_application_date:
      template: :single_question
      questions:
        - name: :sub_section
          title: Date they applied
          current_section: Legal history
          widget: :title
        - name: :other_application_date
          with_title: true
          widget: :date
    other_agency_name:
      template: :single_question
      questions:
        - name: :other_agency_name
          title: Name of agency or service
          current_section: Legal history
          widget: :input
    other_agency_address:
      template: :single_question
      template: :address
      current_section: Legal history
      reference: :other_agency_address
      title: Address of agency or service
      questions:
        - name: :line_1
          title: Address Line 1
          with_title: true
          widget: :input
          model: :address
        - name: :line_2
          title: Address Line 2
          with_title: true
          widget: :input
          model: :address
        - name: :line_3
          title: Address Line 3
          with_title: true
          widget: :input
          model: :address
        - name: :post_town
          title: Address Line 4
          with_title: true
          widget: :input
          model: :address
        - name: :postcode
          title: Postcode
          with_title: true
          widget: :input
    other_type_of_application:
      template: :single_question
      questions:
        - name: :other_type_of_application
          title: Type of application
          current_section: Legal history
          widget: :input
    other_application_outcome:
      template: :single_question
      questions:
        - name: :other_application_outcome
          title: What was the outcome of the application?
          current_section: Legal history
          widget: :input
    previous_fostering:
      template: :single_question
      questions:
        - name: :sub_section
          title: Have you been an approved foster carer in the previous 12 months?
          current_section: Legal history
          widget: :title
        - name: :previous_fostering
          widget: :boolean
          yes_value: Yes
          no_value: No
    previous_agency_name:
      template: :single_question
      questions:
        - name: :previous_agency_name
          title: Name of agency or service
          current_section: Legal history
          widget: :input
    previous_agency_address:
      template: :single_question
      template: :address
      current_section: Legal history
      reference: :previous_agency_address
      title: Address of agency or service
      questions:
        - name: :line_1
          title: Address Line 1
          with_title: true
          widget: :input
        - name: :line_2
          title: Address Line 2
          with_title: true
          widget: :input
        - name: :line_3
          title: Address Line 3
          with_title: true
          widget: :input
        - name: :post_town
          title: Address Line 4
          with_title: true
          widget: :input
        - name: :postcode
          title: Postcode
          with_title: true
          widget: :input
