form:
  name: 'Referees'
  template: :check_if_you_can_foster
  steps:
    intro:
      template: :referee_intro
    name:
      template: :questions
      questions:
        - name: :section
          title: Your %{number} reference
          widget: :title_with_name
        - name: :first_name
          title: First name
          with_title: true
          widget: :input
        - name: :last_name
          title: Last name
          with_title: true
          widget: :input
    reference_address:
      template: :address
      reference: :address
      title: What is %{name}'s address?
      questions:
        - name: :line_1
          title: Address Line 1
          widget: :input
          with_title: true
          model: :address
        - name: :line_2
          title: Address Line 2
          widget: :input
          with_title: true
          model: :address
        - name: :line_3
          title: Address Line 3
          widget: :input
          with_title: true
          model: :address
        - name: :post_town
          title: Address Line 4
          widget: :input
          with_title: true
          model: :address
        - name: :postcode
          title: Postcode
          with_title: true
          widget: :input
    contact:
      template: :questions
      questions:
        - name: :section
          title: Please provide a way to contact %{name}
          widget: :title_with_name
        - name: :email
          title: Email
          with_title: true
          widget: :input
        - name: :phone_number
          title: Phone Number
          with_title: true
          widget: :tel
    reference_relationship:
      template: :questions
      questions:
        - name: :section
          title: Your References
          widget: :title
        - name: :section
          title: What is your relationship to %{name}
          widget: :title_with_name
        - name: :relationship
          widget: :select
        - name: :years_known
          title: How many years have you known each other?
          widget: :input
          with_title: true
