form:
  name: 'Referees'
  template: :check_if_you_can_foster
  steps:
    intro:
      template: :referee_intro
    referees:
      template: :referees
      questions:
        - name: :first_name
          title: First name(s)
          widget: :input
        - name: :last_name
          title: Last name
          widget: :input
        - name: :address
          title: Address
          widget: :address
        - name: :email
          widget: :email
          title: Email
        - name: :phone_number
          title: Phone Number
          widget: :input
        - name: :relationship
          title: Relationship to you
          widget: :select
        - name: :years_known
          title: How many years have you known each other?
          widget: :number_select
          widget: :input
