form:
  name: 'Support Carer'
  template: :check_if_you_can_foster
  steps:
    intro:
      template: :support_carer_intro
    name:
      template: :questions
      questions:
        - name: :section
          title: Your support carer's name
          widget: :title
        - name: :first_name
          title: First name
          model: :support_carer
          with_title: true
          widget: :input
        - name: :last_name
          model: :support_carer
          title: Last name
          with_title: true
          widget: :input
    support_carer_email:
      template: :questions
      questions:
        - name: :section
          title: Your support carer's email address
          widget: :title
        - name: :email
          model: :support_carer
          title: Email
          with_title: true
          widget: :email
