form:
  name: 'Continue'
  template: :check_if_you_can_foster
  steps:
    welcome:
      template: :welcome
    what_is_your_name:
      template: :questions
      questions:
        - name: :section
          widget: :title
          title: Your details
        - name: :first_name
          title: First name
          widget: :input
          with_title: true
          model: :applicant
        - name: :last_name
          title: Last name
          widget: :input
          with_title: true
          model: :applicant
    name_change_info:
      template: :questions
      questions:
        - name: :section
          title: You and your family
          info: You will be asked to provide information about yourself, any partners, family or children.
          widget: :title
        - name: section
          intro: "For this section you will need:"
          list_1: Your address history for the past 7 years
          list_2: National Insurance Number
          widget: :info
    name_change:
      template: :questions
      questions:
        - name: :section
          current_section: About you
          title: Have you ever had any other names?
          widget: :title
        - name: :name_change
          widget: :boolean
          yes_value: Yes
          no_value: Yes
    what_is_your_name_change:
      template: :questions
      questions:
        - name: :section
          current_section: About you
          title: What is your previous full name?
          widget: :title
        - name: :previous_first_name
          title: First name
          widget: :input
          with_title: true
          model: :applicant
        - name: :previous_last_name
          title: Last name
          widget: :input
          with_title: true
          model: :applicant
    previous_name_period:
      template: :questions
      questions:
        - name: :section
          current_section: About you
          title: When did you change your name?
          widget: :title
        - name: :date_changed
          title: Day, Month & Year
          with_title: true
          widget: :date
          model: :applicant
    gender:
      template: :questions
      questions:
        - name: :section
          current_section: About you
          title: What is your gender?
          widget: :title
        - name: :gender
          widget: :radio
          model: :applicant
    dob:
      template: :questions
      questions:
        - name: :section
          current_section: About you
          title: What is your date of birth?
          widget: :title
        - name: :date_of_birth
          title: Date of Birth
          with_title: true
          widget: :date
          model: :applicant
    # country_of_birth:
    #   template: :questions
    #   questions:
    #     - name: :country_of_birth
    #       title: What is your nationality?
    #       current_section: About you
    #       widget: :input
    #       model: :applicant
    town_of_birth:
      template: :questions
      questions:
        - name: :town_of_birth
          title: What is your place of birth?
          current_section: About you
          widget: :input
          model: :applicant
    nationality:
      template: :questions
      title: What is your nationality?
      questions:
        - name: :nationality
          title: What is your nationality?
          current_section: About you
          widget: :input
          model: :applicant
    language:
      template: :questions
      questions:
        - name: :primary_language
          title: What is the main language spoken at home?
          current_section: About you
          widget: :input
    other_language:
      template: :questions
      questions:
        - name: :section
          current_section: About you
          title: Are there other languages spoken at home?
          current_section: About you
          widget: :title
        - name: :other_language
          widget: :boolean
          yes_value: Yes
          no_value: No
    other_language_select:
      template: :questions
      questions:
        - name: :secondary_languages
          title: What other languages are spoken at home?
          current_section: About you
          widget: :input
    are_you_religious:
      template: :single_question
      questions:
        - name: :section
          current_section: About you
          title: Are you religious?
          info: It is helpful for us to know your religious and cultural background. This will be useful when finding the right foster child for you.
          widget: :title
        - name: :religious
          widget: :boolean
          yes_value: Yes
          no_value: No
    what_is_your_religion:
      template: :questions
      questions:
        - name: :religion
          title: What is your religion?
          current_section: About you
          widget: :input
    welcome_working:
      template: :questions
      questions:
        - name: :section
          title: Your employment history
          info: Your lifestyle changes when you foster a child. In order to know how this will impact your working life, we'd like to know about your current employment.
          widget: :title
    employment_history:
      template: :questions
      questions:
        - name: :section
          current_section: Your employment history
          title: What is your employment status?
          widget: :title
        - name: :employment_type
          widget: :radio
    national_insurance:
      template: :questions
      questions:
        - name: :section
          current_section: Your employment history
          title: What is your national insurance number?
          info: Your National Insurance (NI) number is required for background checks of any criminal record.
          widget: :title
        - name: :ni_number
          title: Enter your national insurance number
          with_title: true
          widget: input
    occupation:
      template: :questions
      questions:
        - name: :occupation
          title: What is current occupation?
          current_section: Your employment history
          widget: :input
    name_of_employer:
      template: :questions
      questions:
        - name: :employer
          title: What is the name of your employer or organisation?
          current_section: Your employment history
          widget: :input
    name_of_employer_contact:
      template: :questions
      questions:
        - name: :section
          current_section: Your employment history
          title: Name someone who works with you
          info: You will need one professional reference from someone who works for you regularly.
          widget: :title
        - name: :employer_contact_name
          title: Please provide the full name of your reference
          with_title: true
          widget: :input
    number_for_employer_contact:
      template: :questions
      questions:
        - name: :employer_phone_number
          title: What is the phone number of your reference?
          current_section: Your employment history
          widget: :tel
    email_for_employer_contact:
      template: :questions
      questions:
        - name: :employer_phone_number
          title: What is the email address of your reference?
          current_section: Your employment history
          widget: :email
    address_welcome:
      template: :questions
      questions:
        - name: :section
          title: Your address history
          info: For your background checks and our records, we ask that you provide us with your address history for the last 7 years.
          widget: :title
    full_address:
      template: :address
      reference: :address
      current_section: Your address history
      title: What is your current address?
      questions:
        - name: :line_1
          title: Address Line 1
          with_title: true
          widget: :input
        - name: :line_2
          title: Address Line 2
          with_title: true
          widget: :input
        - name: :line_3
          title: Address Line 3
          with_title: true
          widget: :input
        - name: :post_town
          title: Address Line 4
          with_title: true
          widget: :input
        - name: :postcode
          title: Postcode
          with_title: true
          widget: :input
        - name: :date_from
          title: When did you move into this property?
          widget: :date
    previous_addresses:
      template: :previous_addresses
      questions:
        - name: :line_1
          title: Address Line 1
          with_title: true
          widget: :input
        - name: :line_2
          title: Address Line 2
          with_title: true
          widget: :input
        - name: :line_3
          title: Address Line 3
          with_title: true
          widget: :input
        - name: :post_town
          title: Address Line 4
          with_title: true
          widget: :input
        - name: :postcode
          title: Postcode
          with_title: true
          widget: :input
        - name: :date_from
          title: When did you move into this property?
          widget: :date
        - name: :date_to
          title: When did you move out of this property?
          widget: :date
    your_family:
      template: :questions
      questions:
        - name: :section
          title: Your family
          widget: :title
          info: |
            It is important that other children and adults in your family and household consent to a foster child joining the family.

            If there are adults (over the age of 18), they will be required to have a background check for any criminal record.
    children_at_home:
      template: :questions
      questions:
        - name: :section
          current_section: Your family
          title: Do you have any children under 18 living in the household?
          widget: :title
        - name: :children_at_home
          widget: :boolean
          yes_value: Yes
          no_value: No
    children_living_at_home:
      template: :children
      questions:
        - name: :first_name
          title: First name
          with_title: true
          widget: :input
        - name: :last_name
          title: Last name
          with_title: true
          widget: :input
        - name: :gender
          title: Gender
          widget: :radio
        - name: :date_of_birth
          widget: :date
          title: Date of Birth
        - name: :relationship
          title: Relationship to you
          widget: :select
        - name: :school
          title: Child's School
          with_title: true
          widget: :input
        - name: :school_contact
          title: School phone number
          with_title: true
          widget: :tel
    children_elsewhere:
      template: :questions
      questions:
        - name: :section
          current_section: Your family
          title: Do you have any children under 18 from a previous relationship living elsewhere?
          widget: :title
        - name: :children_living_elsewhere
          widget: :boolean
          yes_value: Yes
          no_value: No
    children_living_elsewhere:
      template: :children_elsewhere
      questions:
        - name: :first_name
          title: First name
          with_title: true
          widget: :input
        - name: :last_name
          title: Last name
          with_title: true
          widget: :input
        - name: :gender
          title: Gender
          widget: :radio
        - name: :date_of_birth
          widget: :date
          title: Date of Birth
        - name: :relationship
          title: Relationship to you
          widget: :select
        - name: :school
          title: Child's School
          with_title: true
          widget: :input
        - name: :school_contact
          title: School phone number
          with_title: true
          widget: :tel
    adults_at_home:
      template: :questions
      questions:
        - name: :section
          current_section: Your family
          title: Are there any adults (over 18) living with you?
          info: Any adults living in the same household will be required to have a background check for any criminal record.
          widget: :title
        - name: :adults_living_at_home
          widget: :boolean
          yes_value: Yes
          no_value: No
    adults_living_at_home:
      template: :adults
      questions:
        - name: :first_name
          title: First name
          with_title: true
          widget: :input
        - name: :last_name
          with_title: true
          title: Last name
          widget: :input
        - name: :gender
          title: Gender
          widget: :radio
        - name: :date_of_birth
          widget: :date
          title: Date of Birth
        - name: :relationship
          title: Relationship to you
          widget: :select
    adults_elsewhere:
      template: :questions
      questions:
        - name: :section
          current_section: Your family
          title: Are there any other adults (over 18) from a previous relationship living elsewhere?
          info: Any adults living elsewhere who visit on a very frequent basis will be required to have a background check for any criminal record.
          widget: :title
        - name: :adults_living_elsewhere
          widget: :boolean
          yes_value: Yes
          no_value: Yes
    adults_living_elsewhere:
      template: :adults_elsewhere
      questions:
        - name: :first_name
          title: First name
          with_title: true
          widget: :input
        - name: :last_name
          title: Last name
          with_title: true
          widget: :input
        - name: :gender
          title: Gender
          widget: :radio
        - name: :date_of_birth
          widget: :date
          title: Date of Birth
        - name: :relationship
          title: Relationship to you
          widget: :select
    pets_welcome:
      template: :questions
      questions:
        - name: :section
          title: Pets
          info: Owning pets and fostering should not be taken lightly. Please provide up-to-date details about your pet(s).
          widget: :title
    pets:
      template: :single_question
      questions:
        - name: :sub_section
          title: Do you have any pets?
          current_section: Your Pets
          widget: :title
        - name: :have_pets
          widget: :boolean
          yes_value: Yes
          no_value: No
        - name: :number_of_pets
          title: How many?
          widget: :number_select
          min_value: 1
          max_value: 10
          classes: 'extra hidden'
        - name: :pet_type
          title: What pets do you have?
          widget: :input
          with_title: true
          classes: 'extra hidden'
