form:
  name: 'Continue'
  template: :check_if_you_can_foster
  steps:
    welcome:
      template: :welcome
    name_change_info:
      template: :questions
      questions:
        - name: :section
          heading: You & your family
          intro: Information will be requested about yourself, any partners, family or children.
          widget: :title
        - name: section
          intro: "For this section we ask you please have the following items prepared:"
          list_1: Your address history for the past 7 years
          list_2: National Insurance Number
          list_3: Contact details for 6 personal references
          widget: :info
    name_change:
      template: :questions
      questions:
        - name: :section
          heading: You & your family
          title: Have you ever had any other names?
          widget: :title
        - name: :name_change
          widget: :boolean
          yes_value: Yes
          no_value: Yes
    what_is_your_name_change:
      template: :questions
      questions:
        - name: :section
          heading: You & your family
          title: What is your previous full name?
          widget: :title
        - name: :previous_first_name
          title: First name(s)
          widget: :input
          model: :applicant
        - name: :previous_last_name
          title: Last name
          widget: :input
          model: :applicant
    previous_name_period:
      template: :questions
      questions:
        - name: :section
          heading: You & your family
          title: When did you change your name?
          widget: :title
        - name: :date_changed
          title: Day, Month & Year
          widget: :date
          model: :applicant
    gender:
      template: :questions
      questions:
        - name: :section
          heading: You & your family
          title: What is your gender?
          widget: :title
        - name: :gender
          widget: :radio
          model: :applicant
    dob:
      template: :questions
      questions:
        - name: :section
          heading: You & your family
          title: What is your date of birth?
          widget: :title
        - name: :date_of_birth
          title: Date of Birth
          widget: :date
          model: :applicant
    country_of_birth:
      template: :questions
      questions:
        - name: :section
          heading: You & your family
          title: What is your country of birth?
          widget: :title
        - name: :country_of_birth
          title: Enter your country of birth
          widget: :input
          model: :applicant
    town_of_birth:
      template: :questions
      questions:
        - name: :section
          heading: You & your family
          title: What is your town of birth?
          widget: :title
        - name: :town_of_birth
          title: Enter your town of birth
          widget: :input
          model: :applicant
    nationality:
      template: :questions
      title: What is your nationality?
      questions:
        - name: :section
          heading: You & your family
          title: What is your nationality?
          widget: :title
        - name: :nationality
          title: Enter your nationality
          widget: :radio
          model: :applicant
    language:
      template: :questions
      questions:
        - name: :section
          heading: You & your family
          title: What is the main language spoken at home?
          widget: :title
        - name: :primary_language
          title: Enter the main language spoken at home
          widget: :input
    other_language:
      template: :questions
      questions:
        - name: :section
          heading: You & your family
          title: Are there other languages spoken at home?
          widget: :title
        - name: :other_language
          widget: :boolean
          yes_value: Yes
          no_value: No
    other_language_select:
      template: :questions
      questions:
        - name: :section
          heading: You & your family
          title: What other languages are spoken at home?
          widget: :title
        - name: :secondary_languages
          title: Enter the other languages spoken at home
          widget: :input
    are_you_religious:
      template: :single_question
      questions:
        - name: :section
          heading: You & your family
          title: Are you religious?
          info: It is helpful for us to know your religious and cultural background. This will be useful when finding the right foster child for you.
          widget: :title
        - name: :religious
          widget: :boolean
          yes_value: Yes
          no_value: No
    what_is_your_religion:
      template: :questions
      questions:
        - name: :section
          heading: You & your family
          title: What is your religion?
          widget: :title
        - name: :religion
          title: Enter your religion
          widget: :input
    welcome_working:
      template: :questions
      questions:
        - name: :section
          heading: Your working experience
          intro: Your lifestyle changes when you foster a child. In order to know how this will impact your working life, we would like to know about your current employment.
          widget: :title
    employment_history:
      template: :questions
      questions:
        - name: :section
          heading: Your working experience
          title: Are you employed?
          widget: :title
        - name: :employment_type
          widget: :radio
    national_insurance:
      template: :questions
      questions:
        - name: :section
          heading: Your working experience
          title: What is your national insurance number?
          info: Your National Insurance (NI) number s required for the DBS background check.
          widget: :title
        - name: :ni_number
          title: Enter your national insurance number
          link: I don't have a National Insurance number
          widget: input
    occupation:
      template: :questions
      questions:
        - name: :section
          heading: Your working experience
          title: What is current occupation?
          widget: :title
        - name: :occupation
          title: Enter your current occupation
          widget: :input
    name_of_employer:
      template: :questions
      questions:
        - name: :section
          heading: Your working experience
          title: What is the name of your employer or organisation?
          widget: :title
        - name: :employer
          title: Enter your employer or organisation
          widget: :input
    name_of_employer_contact:
      template: :questions
      questions:
        - name: :section
          heading: Your working experience
          title: Name someone who works with you.
          info: You will need one professional reference.
          widget: :title
        - name: :employer_contact_name
          title: Please provide the full name of the person you have chosen
          widget: :input
    number_for_employer_contact:
      template: :questions
      questions:
        - name: :section
          heading: Your working experience
          title: What is the phone number or e-mail address of the person you have chosen?
          info: You will need one professional reference.
          widget: :title
        - name: :employer_phone_number
          title: Please provide details to directly contact the person you have chosen
          widget: :input
    address_welcome:
      template: :questions
      questions:
        - name: :section
          heading: Your address history
          intro: For your background checks and our records, we ask that you provide us with your address history for the last 7 years.
          widget: :title
    full_address:
      template: :address
      reference: :address
      title: Your address history
      sub_title: What is your current address?
      questions:
        - name: :line_1
          title: Address Line 1
          widget: :input
        - name: :line_2
          title: Address Line 2
          widget: :input
        - name: :line_3
          title: Address Line 3
          widget: :input
        - name: :post_town
          title: Address Line 4
          widget: :input
        - name: :postcode
          title: Postcode
          widget: :input
        - name: :date_from
          title: When did you move into this property?
          widget: :date
    previous_addresses:
      template: :previous_addresses
      questions:
        - name: :line_1
          title: Address Line 1
          widget: :input
        - name: :line_2
          title: Address Line 2
          widget: :input
        - name: :line_3
          title: Address Line 3
          widget: :input
        - name: :post_town
          title: Address Line 4
          widget: :input
        - name: :date_from
          title: When did you move into this property?
          widget: :date
        - name: :date_to
          title: When did you move out of this property?
          widget: :date
    your_family:
      template: :questions
      questions:
        - name: :section
          heading: Your family
          widget: :title
          intro: It is important that other children and adults in your family and household consent to a foster child joining the family.
          extra: If there are adults (over the age of 18), they will need to have a DBS background check.
    children_living_at_home:
      template: :questions
      questions:
        - name: :section
          heading: Your family
          title: Are there any children under 18 living in the household?
          widget: :title
        - name: :children_at_home
          widget: :boolean
          yes_value: Yes
          no_value: Yes
        - name: :number_of_children
          title: How many?
          widget: :number_select
          min_value: 1
          max_value: 10
    children_living_elsewhere:
      template: :questions
      questions:
        - name: :section
          heading: Your family
          title: Are there any children under 18 from a previous relationship living elsewhere?
          widget: :title
        - name: :children_living_elsewhere
          widget: :boolean
          yes_value: Yes
          no_value: No
        - name: :number_of_children_elsewhere
          title: How many?
          widget: :number_select
          min_value: 1
          max_value: 10
    adults_living_at_home:
      template: :questions
      questions:
        - name: :section
          heading: Your family
          title: Are there any other adults living in the household?
          info: Any adults living in the same household need to undergo a DBS background check.
          widget: :title
        - name: :adults_living_at_home
          widget: :boolean
          yes_value: Yes
          no_value: Yes
        - name: :number_of_adults
          title: How many?
          widget: :number_select
          min_value: 1
          max_value: 10
    adults_living_elsewhere:
      template: :questions
      questions:
        - name: :section
          heading: Your family
          title: Are there any adults (over 18) from a previous relationship living elsewhere?
          info: Any adults living elsewhere who visit on a very frequent basis will be asked to undergo a DBS background check.
          widget: :title
        - name: :adults_living_elsewhere
          widget: :boolean
          yes_value: Yes
          no_value: Yes
        - name: :number_of_adults_elsewhere
          title: How many?
          widget: :number_select
          min_value: 1
          max_value: 10
    pets_welcome:
      template: :questions
      questions:
        - name: :section
          heading: Pets
          intro: Owning pets and fostering should not be taken lightly. Please provide up-to-date details about your pet(s).
          widget: :title
    pets:
      template: :single_question
      questions:
        - name: :section
          heading: Pets
          widget: :title
        - name: :sub_section
          title: Do you have any pets?
          widget: :title
        - name: :have_pets
          widget: :boolean
          yes_value: Yes
          no_value: Yes
        - name: :number_of_pets
          title: How many?
          widget: :number_select
          min_value: 1
          max_value: 10
    breed_pets:
      template: :single_question
      questions:
        - name: :section
          heading: Pets
          widget: :title
        - name: :sub_section
          title: Do you breed pets?
          widget: :title
        - name: :breed_pets
          widget: :boolean
    where_breed_pets:
      template: :single_question
      questions:
        - name: :section
          heading: Pets
          widget: :title
        - name: :sub_section
          title: Where does the breeding take place?
          widget: :title
        - name: :where_breed_pets
          widget: :input
    offspring:
      template: :single_question
      questions:
        - name: :section
          heading: Pets
          widget: :title
        - name: :sub_section
          title: What happens to any offspring? Where are they kept?
          widget: :title
        - name: :offspring_kept
          widget: :textarea
    breeding_risks:
      template: :single_question
      questions:
        - name: :section
          heading: Pets
          widget: :title
        - name: :sub_section
          title: What actions will you take to reduce any risks before a child is placed?
          widget: :title
        - name: :breeding_risks
          widget: :textarea
    breeding_other:
      template: :single_question
      questions:
        - name: :section
          heading: Pets
          widget: :title
        - name: :sub_section
          title: Any other information you consider to be relevant?
          widget: :title
        - name: :breeding_other
          widget: :textarea
